LDFLAGS:=-lboost_system -lboost_thread -pthread

# All Targets
all: bin/BGRsclient

# Tool invocations
# Executable "BGRsclient" depends on the files BGRsclient.o connectionHandler.o echoClient.o
bin/BGRsclient: bin/BGRsclient.o bin/connectionHandler.o bin/inputReader.o bin/SocketReader.o
	@echo 'Building target: BGRsclient'
	@echo 'Invoking: C++ Linker'
	g++ -o bin/BGRsclient bin/BGRsclient.o bin/connectionHandler.o bin/inputReader.o bin/SocketReader.o $(LDFLAGS)
	@echo 'Finished building target: BGRsclient'
	@echo ' '

#connectionHandler.o Depends on the source and header files src/connectionHandler.cpp include/connectionHandler.h
bin/connectionHandler.o: src/connectionHandler.cpp
	g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/connectionHandler.o src/connectionHandler.cpp $(LDFLAGS)

#echoClient.o Depends on the source and header files src/echoClient.cpp include/echoClient.h
bin/BGRsclient.o: src/BGRsclient.cpp
	g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/BGRsclient.o src/BGRsclient.cpp

bin/inputReader.o: src/inputReader.cpp
	g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/inputReader.o src/inputReader.cpp

bin/SocketReader.o: src/SocketReader.cpp
	g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/SocketReader.o src/SocketReader.cpp

#Clean the build directory
clean:
	rm -f bin/*
